### ISSUE TITLE
Some install issues

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godot-nim/minister#2] opened 2024-07-20 19:59 UTC
- [ ] #8
- [x] Issue: godotcore installs correctly, godotgen fails. `Details: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.` and `Error:  'hg' not in PATH`   
  - (suppressed message? `tools.nim(62)            tryDoCmdEx`) 
  - EDIT: Further context for first bit: `Execution of 'git -C /tmp/nimble_253732/_homeUSERNAMEgodotgen rev-parse HEAD' failed with an exit code 128`
  - earlier in the output (just after the detail below) `fatal: Failed to resolve 'HEAD' as a valid ref`. I don't know if it's the case here, but searching that makes it seem like you need to be careful when fixing that to avoid file loss
- [x] Detail: Not sure if related to the issue, but godotgen also spits out a message about wanting an identity. 
  - A bit creepy/unnecessary. If this is some git thing for contributors, maybe re-word (assuming it isn't written by git itself)
  - `Author identity unknown` could be directly caused by the command or branch not being correct

**Comment by panno8M** [comment] 2024-07-25 18:30
@insomniacUNDERSCORElemon 

Thank you for a well organized Issue.

It appears that the problem was running `git commit` during the installation of godotgen.

I have made a change to omit this step as it is not always necessary.

TIPS:
The `Author identity unknown` is an error message that can occur during this process and is generated by running `git commit` without a user name or email set in gitconfig.

**Comment by panno8M** [comment] 2024-07-25 18:31
It is a little difficult to reproduce/test in my local, so a report would be appreciated. If it works, I will close it.

**Comment by insomniacUNDERSCORElemon** [comment] 2024-07-25 23:19
Installs now.

However I am not able to run the tester project, when running `nimble build` it just says `cannot open file: godot`. I did use the 3.X bindings and checked one of my files, it also used a simple `import godot` so that may be clashing but I'm not sure. (could be other stuff like nim version, but I don't know why it'd fail here)

**Comment by panno8M** [comment] 2024-07-26 02:00
@insomniacUNDERSCORElemon 

Perhaps this will work.
Pull godot-nim/demo and try to build it.

**Comment by panno8M** [comment] 2024-07-26 02:02
I am embarrassed by the many elementary flaws:-( So far no one but me has been able to build this project.
It reminds me of the importance of CI.

**Comment by insomniacUNDERSCORElemon** [comment] 2024-07-26 02:54
Better, but:

`dodge_the_creeps_2d/src/gdMob.nim(14, 3) Error: ambiguous call; both system.echo(x: varargs[typed]) [proc declared in /home/lemon/.choosenim/toolchains/nim-2.0.8/lib/system.nim(1846, 6)] and godot.echo(args: varargs[Variant]) [proc declared in /home/username/.nimble/pkgs2/godot-0.1.0-102d0374e8533549200fc188101372277da299ea/godot.nim(13, 6)] match for: (string)`

**Comment by panno8M** [comment] 2024-07-26 03:00
please try again, sir

**Comment by insomniacUNDERSCORElemon** [comment] 2024-07-26 03:06
Works now, but I'm on 4.2 because of updates (I could download and run it from elsewhere, but I assume this wouldn't actually work with the generator?) and it seems like this is still set up for 4.1.

Also you're doing better than me who has no projects started yet. Though I'd guess stuff like this may just be teething issues for the project with it being so early on, especially for what is currently solo.

**Comment by panno8M** [comment] 2024-07-26 03:23
Yes, that's why I have raise godot-nim/godotcore#12.
`choosenim stable` and rebuild will resolve it.

I'll try to fix this bug today, and if it looks too difficult, I'll narrow down the supported version.

**Comment by insomniacUNDERSCORElemon** [comment] 2024-07-26 03:29
> Yes, that's why I have raise [godot-nim/godotcore#12](https://github.com/godot-nim/godotcore/issues/12).
> `choosenim stable` and rebuild will resolve it

2.0.8 [was released on July 3rd](https://nim-lang.org/blog/2024/07/03/version-208-released.html).

`choosenim stable`
`      Info: Version 2.0.8 already selected`

**Comment by panno8M** [comment] 2024-07-26 03:34
Thanks for the info, will update choosenim.
The correct is `choosenim 2.0.0`. I have not yet tested what happens with these intermediate versions.

**Comment by insomniacUNDERSCORElemon** [comment] 2024-07-26 03:43
Alright, now it launches with 2.0.0. I like the music/sounds.

How are scripts attached? Just create gdNodeName and import+register in project_name.nim?

**Comment by panno8M** [comment] 2024-07-26 03:54
That is correct.

Functions that Godot needs to know should be marked with {.gdsync.} {.name: “XXX”.} can override the name.

It may also be noted that there are two project-related settings, project.nimble and config.nims.

Once the support for 2.0.8 is complete, we will start working on the project template and development documentation.

**Comment by panno8M** [comment] 2024-07-26 03:57
As for the project name, it is a bit complicated.

It can actually be anything as long as the name of the bin variable in *.nimble and the path to so in *.gdextension match.

**Comment by panno8M** [comment] 2024-07-26 09:00
@insomniacUNDERSCORElemon 

Support for nim 2.0.8 is complete.
Interestingly, the code before the fix seemed to work thanks to a bug on the nim side.

It will work after reverting to 2.0.8.

**Closed** 2024-07-26 21:02 UTC

**Comment by insomniacUNDERSCORElemon** [comment] 2024-07-26 22:10
> It will work after reverting to 2.0.8

I tried this and am still getting the `=destroy` issue on launch. I mainly did that because I needed to rebuild nimlsp anyway, but I can stick with 2.0.0.
